---
- name: sh int and ver
  hosts: routers
  gather_facts: false
  tasks:
    - name: Send Command
      cisco.ios.ios_command:
        commands:
          - show version
          - show ip interface brief
      register: output

    - name: show output
      ansible.builtin.debug:
        var: output
